name: tproger_mobile_app
description: Mobile app for tproger.ru
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  html: ^0.15.0
  http: ^0.13.4

dev_dependencies:
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
